/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * API server artifact
 */
export class Artifact extends SpeakeasyBase {
    /**
     * execution name that produced the artifact
     */
    @SpeakeasyMetadata()
    @Expose({ name: "executionName" })
    executionName?: string;

    /**
     * artifact file path
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * file size in bytes
     */
    @SpeakeasyMetadata()
    @Expose({ name: "size" })
    size?: number;
}
