/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Testkube internal reference for data in Kubernetes config maps
 */
export class ConfigMapRef extends SpeakeasyBase {
    /**
     * object key
     */
    @SpeakeasyMetadata()
    @Expose({ name: "key" })
    key: string;

    /**
     * object name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * object kubernetes namespace
     */
    @SpeakeasyMetadata()
    @Expose({ name: "namespace" })
    namespace?: string;
}
