/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum EventType {
    StartTest = "start-test",
    EndTestSuccess = "end-test-success",
    EndTestFailed = "end-test-failed",
    EndTestAborted = "end-test-aborted",
    EndTestTimeout = "end-test-timeout",
    StartTestsuite = "start-testsuite",
    EndTestsuiteSuccess = "end-testsuite-success",
    EndTestsuiteFailed = "end-testsuite-failed",
    EndTestsuiteAborted = "end-testsuite-aborted",
    EndTestsuiteTimeout = "end-testsuite-timeout",
    Created = "created",
    Updated = "updated",
    Deleted = "deleted",
}
