/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ExecutorMeta } from "./executormeta";
import { LocalObjectReference } from "./localobjectreference";
import { Expose, Type } from "class-transformer";

export enum ExecutorFeatures {
    Artifacts = "artifacts",
    JunitReport = "junit-report",
}

/**
 * CRD based executor data
 */
export class Executor extends SpeakeasyBase {
    /**
     * additional executor binary argument
     */
    @SpeakeasyMetadata()
    @Expose({ name: "args" })
    args?: string[];

    /**
     * executor image command
     */
    @SpeakeasyMetadata()
    @Expose({ name: "command" })
    command?: string[];

    /**
     * list of handled content types
     */
    @SpeakeasyMetadata()
    @Expose({ name: "contentTypes" })
    contentTypes?: string[];

    /**
     * ExecutorType one of "rest" for rest openapi based executors or "job" which will be default runners for testkube soon
     */
    @SpeakeasyMetadata()
    @Expose({ name: "executorType" })
    executorType?: string;

    /**
     * Available executor features
     */
    @SpeakeasyMetadata()
    @Expose({ name: "features" })
    features?: ExecutorFeatures[];

    /**
     * Image for kube-job
     */
    @SpeakeasyMetadata()
    @Expose({ name: "image" })
    image?: string;

    /**
     * container image pull secrets
     */
    @SpeakeasyMetadata({ elemType: LocalObjectReference })
    @Expose({ name: "imagePullSecrets" })
    @Type(() => LocalObjectReference)
    imagePullSecrets?: LocalObjectReference[];

    /**
     * Job template to launch executor
     */
    @SpeakeasyMetadata()
    @Expose({ name: "jobTemplate" })
    jobTemplate?: string;

    /**
     * executor labels
     */
    @SpeakeasyMetadata()
    @Expose({ name: "labels" })
    labels?: Record<string, string>;

    /**
     * Executor meta data
     */
    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    @Type(() => ExecutorMeta)
    meta?: ExecutorMeta;

    /**
     * Types defines what types can be handled by executor e.g. "postman/collection", ":curl/command" etc
     */
    @SpeakeasyMetadata()
    @Expose({ name: "types" })
    types?: string[];

    /**
     * URI for rest based executors
     */
    @SpeakeasyMetadata()
    @Expose({ name: "uri" })
    uri?: string;
}
