/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AssertionResult } from "./assertionresult";
import { Expose, Type } from "class-transformer";

/**
 * execution step status
 */
export enum ExecutionStepResultStatus {
    Passed = "passed",
    Failed = "failed",
}

/**
 * execution result data
 */
export class ExecutionStepResult extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: AssertionResult })
    @Expose({ name: "assertionResults" })
    @Type(() => AssertionResult)
    assertionResults?: AssertionResult[];

    @SpeakeasyMetadata()
    @Expose({ name: "duration" })
    duration?: string;

    /**
     * step name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * execution step status
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: ExecutionStepResultStatus;
}
