/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * various execution counters
 */
export class ExecutionsTotals extends SpeakeasyBase {
    /**
     * the total number of failed executions available
     */
    @SpeakeasyMetadata()
    @Expose({ name: "failed" })
    failed: number;

    /**
     * the total number of passed executions available
     */
    @SpeakeasyMetadata()
    @Expose({ name: "passed" })
    passed: number;

    /**
     * the total number of queued executions available
     */
    @SpeakeasyMetadata()
    @Expose({ name: "queued" })
    queued: number;

    /**
     * the total number of executions available
     */
    @SpeakeasyMetadata()
    @Expose({ name: "results" })
    results: number;

    /**
     * the total number of running executions available
     */
    @SpeakeasyMetadata()
    @Expose({ name: "running" })
    running: number;
}
