/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * optional status filter containing multiple values separated by comma
 */
export enum ExecutionStatus {
    Queued = "queued",
    Running = "running",
    Passed = "passed",
    Failed = "failed",
    Aborted = "aborted",
    Timeout = "timeout",
}
