/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ExecutionsResult } from "./executionsresult";
import { Executor } from "./executor";
import { Expose, Type } from "class-transformer";

/**
 * Executor details with Executor data and additional information like list of executions
 */
export class ExecutorDetails extends SpeakeasyBase {
    /**
     * the result for a page of executions
     */
    @SpeakeasyMetadata()
    @Expose({ name: "executions" })
    @Type(() => ExecutionsResult)
    executions?: ExecutionsResult;

    /**
     * CRD based executor data
     */
    @SpeakeasyMetadata()
    @Expose({ name: "executor" })
    @Type(() => Executor)
    executor?: Executor;

    /**
     * Executor name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}
