/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ExecutionsMetricsExecutions } from "./executionsmetricsexecutions";
import { Expose, Type } from "class-transformer";

export class ExecutionsMetrics extends SpeakeasyBase {
    /**
     * 50th percentile of all durations
     */
    @SpeakeasyMetadata()
    @Expose({ name: "executionDurationP50" })
    executionDurationP50?: string;

    /**
     * 50th percentile of all durations in milliseconds
     */
    @SpeakeasyMetadata()
    @Expose({ name: "executionDurationP50ms" })
    executionDurationP50ms?: number;

    /**
     * 90th percentile of all durations
     */
    @SpeakeasyMetadata()
    @Expose({ name: "executionDurationP90" })
    executionDurationP90?: string;

    /**
     * 90th percentile of all durations in milliseconds
     */
    @SpeakeasyMetadata()
    @Expose({ name: "executionDurationP90ms" })
    executionDurationP90ms?: number;

    /**
     * 95th percentile of all durations
     */
    @SpeakeasyMetadata()
    @Expose({ name: "executionDurationP95" })
    executionDurationP95?: string;

    /**
     * 95th percentile of all durations in milliseconds
     */
    @SpeakeasyMetadata()
    @Expose({ name: "executionDurationP95ms" })
    executionDurationP95ms?: number;

    /**
     * 99th percentile of all durations
     */
    @SpeakeasyMetadata()
    @Expose({ name: "executionDurationP99" })
    executionDurationP99?: string;

    /**
     * 99th percentile of all durations in milliseconds
     */
    @SpeakeasyMetadata()
    @Expose({ name: "executionDurationP99ms" })
    executionDurationP99ms?: number;

    /**
     * List of test/testsuite executions
     */
    @SpeakeasyMetadata({ elemType: ExecutionsMetricsExecutions })
    @Expose({ name: "executions" })
    @Type(() => ExecutionsMetricsExecutions)
    executions?: ExecutionsMetricsExecutions[];

    /**
     * failed executions number
     */
    @SpeakeasyMetadata()
    @Expose({ name: "failedExecutions" })
    failedExecutions?: number;

    /**
     * Percentage pass to fail ratio
     */
    @SpeakeasyMetadata()
    @Expose({ name: "passFailRatio" })
    passFailRatio?: number;

    /**
     * total executions number
     */
    @SpeakeasyMetadata()
    @Expose({ name: "totalExecutions" })
    totalExecutions?: number;
}
