/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TestTriggerConditionStatuses } from "./testtriggerconditionstatuses";
import { Expose } from "class-transformer";

/**
 * supported condition for test triggers
 */
export class TestTriggerCondition extends SpeakeasyBase {
    /**
     * test trigger condition reason
     */
    @SpeakeasyMetadata()
    @Expose({ name: "reason" })
    reason?: string;

    /**
     * supported kubernetes condition statuses for test triggers
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: TestTriggerConditionStatuses;

    /**
     * duration in seconds in the past from current time when the condition is still valid
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ttl" })
    ttl?: number;

    /**
     * test trigger condition
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: string;
}
