/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TestSuiteBatchStepExecutionSummary } from "./testsuitebatchstepexecutionsummary";
import { TestSuiteExecutionStatus } from "./testsuiteexecutionstatus";
import { Expose, Transform, Type } from "class-transformer";

/**
 * Test execution summary
 */
export class TestSuiteExecutionSummary extends SpeakeasyBase {
    /**
     * test suite execution duration
     */
    @SpeakeasyMetadata()
    @Expose({ name: "duration" })
    duration?: string;

    /**
     * test suite execution duration in ms
     */
    @SpeakeasyMetadata()
    @Expose({ name: "durationMs" })
    durationMs?: number;

    /**
     * test suite execution end time
     */
    @SpeakeasyMetadata()
    @Expose({ name: "endTime" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    endTime?: Date;

    @SpeakeasyMetadata({ elemType: TestSuiteBatchStepExecutionSummary })
    @Expose({ name: "execution" })
    @Type(() => TestSuiteBatchStepExecutionSummary)
    execution?: TestSuiteBatchStepExecutionSummary[];

    /**
     * execution id
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * test suite and execution labels
     */
    @SpeakeasyMetadata()
    @Expose({ name: "labels" })
    labels?: Record<string, string>;

    /**
     * execution name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * test suite execution start time
     */
    @SpeakeasyMetadata()
    @Expose({ name: "startTime" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    startTime?: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: TestSuiteExecutionStatus;

    /**
     * name of the test suite
     */
    @SpeakeasyMetadata()
    @Expose({ name: "testSuiteName" })
    testSuiteName: string;
}
