/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ObjectRef } from "./objectref";
import { TestSuiteStepDelayV2 } from "./testsuitestepdelayv2";
import { Expose, Type } from "class-transformer";

export class TestSuiteStepV2 extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "delay" })
    @Type(() => TestSuiteStepDelayV2)
    delay?: TestSuiteStepDelayV2;

    @SpeakeasyMetadata()
    @Expose({ name: "execute" })
    @Type(() => ObjectRef)
    execute?: ObjectRef;

    @SpeakeasyMetadata()
    @Expose({ name: "stopTestOnFailure" })
    stopTestOnFailure?: boolean;
}
