/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ExecutionCore } from "./executioncore";
import { Expose, Type } from "class-transformer";

/**
 * test status
 */
export class TestStatus extends SpeakeasyBase {
    /**
     * test execution core
     */
    @SpeakeasyMetadata()
    @Expose({ name: "latestExecution" })
    @Type(() => ExecutionCore)
    latestExecution?: ExecutionCore;
}
