/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Execution } from "./execution";
import { ObjectRef } from "./objectref";
import { TestSuiteStep } from "./testsuitestep";
import { Expose, Type } from "class-transformer";

/**
 * execution result returned from executor
 */
export class TestSuiteStepExecutionResult extends SpeakeasyBase {
    /**
     * test execution
     */
    @SpeakeasyMetadata()
    @Expose({ name: "execution" })
    @Type(() => Execution)
    execution?: Execution;

    @SpeakeasyMetadata()
    @Expose({ name: "step" })
    @Type(() => TestSuiteStep)
    step?: TestSuiteStep;

    @SpeakeasyMetadata()
    @Expose({ name: "test" })
    @Type(() => ObjectRef)
    test?: ObjectRef;
}
