/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class TestSuiteStep extends SpeakeasyBase {
    /**
     * delay duration in time units
     */
    @SpeakeasyMetadata()
    @Expose({ name: "delay" })
    delay?: string;

    /**
     * object name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "test" })
    test?: string;
}
