/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * supported probe for test triggers
 */
export class TestTriggerProbe extends SpeakeasyBase {
    /**
     * test trigger condition probe headers to submit
     */
    @SpeakeasyMetadata()
    @Expose({ name: "headers" })
    headers?: Record<string, string>;

    /**
     * test trigger condition probe host, default is pod ip or service name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "host" })
    host?: string;

    /**
     * test trigger condition probe path to check, default is /
     */
    @SpeakeasyMetadata()
    @Expose({ name: "path" })
    path?: string;

    /**
     * test trigger condition probe port to connect
     */
    @SpeakeasyMetadata()
    @Expose({ name: "port" })
    port?: number;

    /**
     * test trigger condition probe scheme to connect to host, default is http
     */
    @SpeakeasyMetadata()
    @Expose({ name: "scheme" })
    scheme?: string;
}
