/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TestSuiteStep } from "./testsuitestep";
import { Expose, Type } from "class-transformer";

/**
 * set of steps run in parallel
 */
export class TestSuiteBatchStep extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: TestSuiteStep })
    @Expose({ name: "execute" })
    @Type(() => TestSuiteStep)
    execute?: TestSuiteStep[];

    @SpeakeasyMetadata()
    @Expose({ name: "stopOnFailure" })
    stopOnFailure: boolean;
}
