/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TestSourceUpsertRequest } from "./testsourceupsertrequest";
import { Expose, Type } from "class-transformer";

/**
 * Test source batch request
 */
export class TestSourceBatchRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: TestSourceUpsertRequest })
    @Expose({ name: "batch" })
    @Type(() => TestSourceUpsertRequest)
    batch: TestSourceUpsertRequest[];
}
