/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Execution } from "./execution";
import { Test } from "./test";
import { Expose, Type } from "class-transformer";

/**
 * Test with latest Execution result
 */
export class TestWithExecution extends SpeakeasyBase {
    /**
     * test execution
     */
    @SpeakeasyMetadata()
    @Expose({ name: "latestExecution" })
    @Type(() => Execution)
    latestExecution?: Execution;

    @SpeakeasyMetadata()
    @Expose({ name: "test" })
    @Type(() => Test)
    test: Test;
}
