/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TestTriggerCondition } from "./testtriggercondition";
import { Expose, Type } from "class-transformer";

export class TestTriggerConditionSpec extends SpeakeasyBase {
    /**
     * list of test trigger conditions
     */
    @SpeakeasyMetadata({ elemType: TestTriggerCondition })
    @Expose({ name: "conditions" })
    @Type(() => TestTriggerCondition)
    conditions?: TestTriggerCondition[];

    /**
     * duration in seconds the test trigger waits between condition checks
     */
    @SpeakeasyMetadata()
    @Expose({ name: "delay" })
    delay?: number;

    /**
     * duration in seconds the test trigger waits for conditions, until its stopped
     */
    @SpeakeasyMetadata()
    @Expose({ name: "timeout" })
    timeout?: number;
}
