/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * supported test resources for test triggers
 */
export enum TestTriggerExecutions {
    Test = "test",
    Testsuite = "testsuite",
}
