/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class ExecuteTestsRequest extends SpeakeasyBase {
    /**
     * body passed to configure executions
     */
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    executionRequestInput: shared.ExecutionRequestInput;

    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=concurrency" })
    concurrency?: number;

    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=executionSelector" })
    executionSelector?: string;

    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=namespace" })
    namespace?: string;

    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=selector" })
    selector?: string;
}

export class ExecuteTestsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * successful operation
     */
    @SpeakeasyMetadata({ elemType: shared.ExecutionResult })
    executionResults?: shared.ExecutionResult[];

    /**
     * problem with request body
     */
    @SpeakeasyMetadata({ elemType: shared.Problem })
    problems?: shared.Problem[];

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
