/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetTestSuiteExecutionArtifactsRequest extends SpeakeasyBase {
    /**
     * unique id of the object execution
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=executionID" })
    executionID: string;
}

export class GetTestSuiteExecutionArtifactsResponse extends SpeakeasyBase {
    /**
     * successful operation
     */
    @SpeakeasyMetadata()
    artifact?: shared.Artifact;

    @SpeakeasyMetadata()
    contentType: string;

    /**
     * problem with getting test suite executions from storage
     */
    @SpeakeasyMetadata({ elemType: shared.Problem })
    problems?: shared.Problem[];

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
