/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class UpdateConfigKeyResponse extends SpeakeasyBase {
    /**
     * update successful
     */
    @SpeakeasyMetadata()
    config?: shared.Config;

    @SpeakeasyMetadata()
    contentType: string;

    /**
     * problem with input
     */
    @SpeakeasyMetadata({ elemType: shared.Problem })
    problems?: shared.Problem[];

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
